# Model
transformer: huggingface
transformer_conf:
    hf_model_tag: Qwen/Qwen3-0.6B-Base
    activation_checkpointing: false
    attention_choice: flash_attention_2

corelm: ar_delay
corelm_conf:
    share_emb: false

# loss
modality_weights: {
    "g2p": 1.0,
    "codec": 0.125,
    "text_bpe": 1.0,
    "image": 1.0,
    "special_token": 10.0,
}
loss_region: target

# General Dataloader configuration
batch_type: numel
batch_bins: 8000
num_iters_per_epoch: 24000
epoch_this_run: 1
max_epoch: 50
num_workers: 6
drop_last_iter: true
log_interval: 100

# Data preprocessing
codec_token_per_frame: 8
codec_token_in_use: 8
image_token_per_patch: 4
speaker_prompt_length: 500

# specaug
asr_apply_time_mask: true
asr_time_mask_config:
    mask_width_ratio_range:
    - 0.
    - 0.05
    num_mask: 10

# deepspeed
use_deepspeed: true
deepspeed_config: conf/deepspeed_ddp_zero1.json
deepspeed_step_sync: false
