frontend: codec     # embedding + positional encoding
frontend_conf:
    hf_model_tag: espnet/amuse_encodec_16k
    token_bias: 2
    patch_size: 8
    positional_dropout_rate: 0.1

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model: discrete_asr
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    patch_size: 8
    length_normalized_loss: false
    share_decoder_input_output_embed: false
    share_encoder_decoder_input_embed: false
    extract_feats_in_collect_stats: false

use_amp: false
unused_parameters: true
log_interval: 1000
batch_type: numel
batch_bins: 10000000000
accum_grad: 1
max_epoch: 100
num_att_plot: 0
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000
